### PR TITLE
chore: bump to php 7.4, guzzle 7, phpunit 9

### PR DESCRIPTION
**Pull request by StephaneBour**

### CODE REVIEW

**Comment by StephaneBour** [comment]
close #99

**Comment by StephaneBour** [comment]
@VincentCasse

**Comment by bistory** [comment]
Unfortunately, I have little to no hope this will be integrated into this branch as not PR have been merged for a while.
I'm "stealing" your fixes to start a fork at https://github.com/wikeo/php-ovh ...

**Comment by StephaneBour** [comment]
@bistory I have hope by chatting with @VincentCasse on other channels 🤞🏻

**Comment by bistory** [comment]
@StephaneBour still nothing ?...

**Comment by StephaneBour** [comment]
@VincentCasse ?

**Comment by StephaneBour** [comment]
@bistory I opened a support ticket, and I contacted our sales representative to try to unblock things. I hope things will move. Ultimately, a tweet to @olesovhcom ?

**Comment by rbeuque74** [comment]
Hello / Bonjour :)

Sorry for being idle on this repository :disappointed: 

I had a look at the pull-request, the requirements modifications are fine to me, the rest is just linting, which is fine too.
Tests are not passing: I tried with our previous test command (`phing test -Donly.units=true`), found a bug :

```
Buildfile: /php-ovh/build.xml

ovh/ovh > test:

ovh/ovh > phpunit:

  [phpunit] Testsuite: Ovh\tests\ApiTest
  [phpunit] Tests run: 18, Failures: 0, Errors: 2, Incomplete: 0, Skipped: 0, Time elapsed: 3.77927 s
  [phpunit] testIfConsumerKeyIsReplace ERROR
  [phpunit] Array to string conversion
  [phpunit] testMissingOvhApplicationHeaderOnRequestCredentials ERROR
  [phpunit] Trying to access array offset on value of type null
  [phpunit] Total tests run: 18, Failures: 0, Errors: 2, Incomplete: 0, Skipped: 0, Time elapsed: 3.78069 s
[phingcall] /php-ovh/build.xml:106:9: Test ERROR (testMissingOvhApplicationHeaderOnRequestCredentials in class Ovh\tests\ApiTest): Trying to access array offset on value of type null

BUILD FAILED
/php-ovh/build.xml:30:37: Execution of the target buildfile failed. Aborting.

Total time: 3.8478 seconds
```

Seems that the error is introduced by the migration to PHP 7.4, which is adding a new Notice: `Trying to access array offset on value of type null`

I added the fix to the pull-request, but there is still some errors, due to the fact that functional tests are now run with `phpunit`, while they were skipped in `phing test` (cf https://github.com/ovh/php-ovh/blob/master/build.xml#L84-L92).

I changed .travis.yml to run tests only on `tests/ApiTest.php`.
As I'm not a PHP expert, I don't know if it's possible to switch to `phpunit`, while keeping the configuration of `build.xml`, or not.
Furthermore, is it mandatory to switch to `phpunit`: what kind of advantages it offers in comparaison to `phing` ?

I also changed some of your type declaration of return value, as `get` `post` `put` `delete` and `decodeResponse` doesn't always return an `array`, it can be a `string`, an `integer` or `null`.
Not sure if that's OK.

Let me know.

Romain

**Review by rbeuque74 — APPROVED** [review]

**Comment by StephaneBour** [comment]
hello @rbeuque74

thank you for having resurrected the project !

**Comment by bistory** [comment]
Thanks @StephaneBour and @rbeuque74 for this ! 🥇

**Comment by rbeuque74** [comment]
Version 3.0.0 is released so you can use it in your dependency managers.

Enjoy
Romain

**Pull request merged**
