### PR TITLE
Add missing "clone" in tests instructions

### PR DESCRIPTION
**Pull request by bistory**
Hi,
This is just a small fix in the "How to run tests?" section.
The git command instruction is missing ;-)

### CODE REVIEW

**Comment by rbeuque74** [comment]
Hello @bistory,
Thanks for your contribution.

Can you please follow the [Contributions guildelines](https://github.com/ovh/php-ovh/blob/master/CONTRIBUTING.rst), especially the `Developer Certificate of Origin`.

Thanks,
Romain

**Review by rbeuque74 — CHANGES_REQUESTED** [review]
Missing DCO

**Comment by rbeuque74** [comment]
Closing as no answer from the pull-request author.
Feel free to reopen if it still applies

**Comment by bistory** [comment]
Yeah sorry but such a complete process for 5 added characters to fix the documentation is boring and useless... You can add them yourself, I don't need to get any attribution...

**Pull request closed without merging**
