### PR TITLE
Guzzle6 for v2.x branch

### PR DESCRIPTION
**Pull request by VincentCasse**
Guzzle6 was not include into php wrapper because of changes in Exception after Guzzle6 release.

Now, that's time to upgrade!

Thanks to @ByScripts work on https://github.com/ovh/php-ovh/pull/17, we include Guzzle6 into our wrapper.

### CODE REVIEW

**Comment by yadutaf** [comment]
Love this ! Go go go.

**Comment by VincentCasse** [comment]
@yadutaf now, travis checks are good. Can you check this pull request please?

**Comment by yadutaf** [comment]
LGTM

**Comment by VincentCasse** [comment]
Welcome to 2.x.x branch :)

**Pull request merged**
