### PR TITLE
Update to Guzzle 6.0 and add 100% code coverage

### PR DESCRIPTION
**Pull request by ByScripts**
I rewritten the API to support the new Guzzle 6.0
I also added 100% code coverage and completed the PhpDoc and type hintings

No method name has changed, only the to request with Guzzle.

Since Guzzle 6.0 is clearly not complatible with <6.0, I think this PR should be on a new dev branch (and a new major version )

### CODE REVIEW

**Comment by ByScripts** [comment]
It seems there is a TLS problem on travis (which make tests failing)

`cURL error 35: gnutls_handshake() failed: A TLS fatal alert has been received. `

**Comment by VincentCasse** [comment]
Hi ByScript,

Definitively, we had to migrate to guzzle6 and PSR-7.
I think we need first to deploy guzzle6 in a dev branch to have more feedback before built a new major version.
@yadutaf: what do you think about this roadmap?

I will check why travis checks doesn't work in few days. Don't hesitate to check too!

Thanks for your contribution!

**Comment by yadutaf** [comment]
:+1: Branches are good. Use them :)

**Comment by BenoitLeveque** [comment]
@VincentCasse any update on this PR ?

i would love to use your api, but i already use guzzle 6 for the other API i consume in my application

**Comment by VincentCasse** [comment]
Guzzle 6 is really a major release. I think we cannot include it into a minor version.

Maybe that's time to begin a 2.x.x branches and keep 1.x.x alive for people who want to use guzzle >= 5

**Pull request closed without merging**
