### PR TITLE
Use a PHP build tool, Phing instead of Grunt.

### PR DESCRIPTION
**Pull request by shulard**
As I already mentioned in the #35 issue, I think it's more suitable to use a PHP build tool instead of a JS one. I don't tell that Grunt is not a powerful tool but it's a complicated installation process to be able to run tests.

Phing is required as a composer package and can be run directly after the `composer install`.

Examples:
```bash
vendor/bin/phing
vendor/bin/phing test
vendor/bin/phing clean
vendor/bin/phing phplint
vendor/bin/phing phpcs
vendor/bin/phing phpunit
vendor/bin/phing phpunit -Donly.units=true #The travis test process
```

The only difference here is the watch process. Phing doesn't have that kind of feature. It can be emulated with different tasks but require a lot more work. I think that PR is the first step, maybe we can go further if necessary.

### CODE REVIEW

**Comment by shulard** [comment]
Hello !

I've just commit a little doc update to trigger a new travis build. I think that the time delta check is too fragile to be integrated as a reference in unit tests. I've had a build [which failed](https://travis-ci.org/ovh/php-ovh/jobs/120919509) just because of a little delay. No problem in the code... Do you think it can be updated to be more solid ?

**Comment by VincentCasse** [comment]
Hi @shulard,

First of all, thanks fo this works. Thats works well and be more compliant with PHP world. So I will merge your PR. But before, can you squash and sign your commit (git commit -s to sign a commit)?

For the test, we were looking for a solution but don't have find a solution to mock  date php functions. We need to be sure that this function is inside the wrapper because that's an important part of the authentication.

Best regards,
Vincent

**Comment by shulard** [comment]
Ok, I've squashed my commits and signed it :smile:

For the native function mock problem you should consider using Atoum as a testing framework. It's one of it's native features: http://atoum.org/features.html#mocks

I've just spend some time investigating the error but just found that it's a little delay difference in the execution which make the build failed. I think that the test suite we'll be more solid without relying on a (possible) moving value.

**Comment by VincentCasse** [comment]
I don't know about Atom. I think that's a better tool to mock php than phpunit but, I'm worry by the small community around Atom.

I think it will be more difficult to developers to participate because of learning curve of Atom (of course if they already know phpunit)

**Comment by shulard** [comment]
The community around atom is not so small :smile:. Indeed it's used in the whole @hoaproject and in a diversity of project. All @atoum users are agreeing about one thing: try it and you'll love it.

You're test suite is simple and you haven't a lot of test cases, I don't think that using @atoum instead of @phpunit block users to participate :smile:.

**Pull request merged**
