### PR TITLE
Handle custom headers in a request and fix ovh-eu url

### PR DESCRIPTION
**Pull request by carsso**
I've added a new parameter to handle custom headers to send to the api.
Also, the ovh-eu API url is the old one.

### CODE REVIEW

**Comment by Rbeuque74** [comment]
Looks good.
Could you add some tests for CI please ?

Thanks

**Comment by Rbeuque74** [comment]
\+ sign commits (git commit -as --amend)   see [CONTRIBUTING.rst](https://github.com/ovh/php-ovh/blob/master/CONTRIBUTING.rst)

**Comment by VincentCasse** [comment]
Please test your patch. I'm not sure unauthentication works well with it

**Comment by Rbeuque74** [comment]
@VincentCasse Not sure, cause in all methods, is_authentificated was using default value, that was "true"

**Comment by VincentCasse** [comment]
Yes but it's forced on line 317 for instance.

**Comment by carsso** [comment]
In rawCall, when the $is_authenticated variable is omitted, it equals "true", so I'm not changing anything in the behaviour by "forcing" a "true" value.

**Comment by VincentCasse** [comment]
Hum, you're right. Sorry, I thought I had manage it.

So, good to merge :)

**Comment by carsso** [comment]
Yaaaay :) Thanks

Woops, I've forgotten the PHPDoc..., I will make another PR to fix this.

**Comment by VincentCasse** [comment]
I fix it in my PR :)

**Pull request merged**
