### PR TITLE
Remove a direct client call, use API `get` method.

### PR DESCRIPTION
**Pull request by shulard**
Remove the `$this->http_client->get()` call used in the `calculateTimeDelta` method.

This call was too coupled to the Http client, using the same method for all the calls is always better.

### CODE REVIEW

**Comment by yadutaf** [comment]
LGTM. Can you sign your commits ?

**Comment by VincentCasse** [comment]
Good for me too. We will merge it when your commit will be signed ( git commit -s )

**Comment by shulard** [comment]
Hello,

I've pushed the new signed commits.

**Comment by VincentCasse** [comment]
Hi @shulard,

Thanks a lot for this contribution :)

Merged

**Pull request merged**
