### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by neoteknic**
Fix for guzzle 7 / laravel 8

### CODE REVIEW

**Comment by bistory** [comment]
Did you achieve to run unit tests ? They miserably fail on my side...

**Comment by MichaelBelgium** [comment]
Please merge asap 🙏

**Comment by bistory** [comment]
I don't think this repo is maintained anymore...

**Comment by rbeuque74** [comment]
Hello,
Thanks for your contribution.
Will be merged via #106.

Closing this one.
Romain

**Pull request closed without merging**
