### PR TITLE
Fix time sensitive unit test

### PR DESCRIPTION
**Pull request by VincentCasse**

### CODE REVIEW

**Comment by stof** [comment]
there is a drawback for this: the ``time()`` function will be replaced for other tests too, which may create weird side effects.

A better solution IMO would be to change the ``assertEquals`` assertion to make it accept a 1s difference:

```php
$this->assertEquals($delay * -1, $time_delta, '', 1)
```

**Comment by VincentCasse** [comment]
Add a difference in the assertEquals is not a good solution: you delay could be greater than one second.. So, that's complicated to define the acceptable difference...

I change a little the unit test to disable the mock just after the test.
The mock is done only inside this test and, if mock is persistent, is disable to avoid to create side effects on others tests.

**Comment by stof** [comment]
@VincentCasse I don't think that the test sensitivity can really be bigger than 1s. the only sensitivity is for the case where the clock changes second between both calls to ``time()`` in the test setup and the execution of the method. If the difference is bigger than 1s, it means that either your code is buggy (so the test should fail), or the code took more than 1s to execute until reaching the second call (so that the clock advances twice), which I would also consider a buggy behavior.

and the way mocking functions works is persistent (such mocking tools make their best to revert back to the original function in other tests)

**Comment by VincentCasse** [comment]
I close this pull request because the discussion doesn't change from few month. Please open a new discussion if you have any new elements.

**Pull request closed without merging**
