### PR TITLE
Fix deprecated function build_query()

### PR DESCRIPTION
**Pull request by malohtie**
See #110

### CODE REVIEW

**Review by peter279k — APPROVED** [review]

**Review by gponty — APPROVED** [review]

**Review by ITCONSULTINGAJACCCIO — APPROVED** [review]

**Comment by MJBGO** [comment]
Can somebody merge this ? It's a blocking issue with newest Guzzle ... Thanks

**Comment by nuclimedia** [comment]
6 month after fix and it still unmerged, please its a deprecated function that ends in a fatal error.

**Comment by MJBGO** [comment]
@rbeuque74 could you merge it please ?

**Comment by MJBGO** [comment]
Is somebody at OVH still maintaining this ? It's a blocking issue in 2022 ...

**Comment by rbeuque74** [comment]
Fixed via #116 

Sorry for the delay.
Romain

**Pull request closed without merging**
