### PR TITLE
Added HHVM to Travis.

### PR DESCRIPTION
**Pull request by h4cc**
Lets see if it works with HHVM :dancer:

### CODE REVIEW

**Comment by h4cc** [comment]
Yehaaa! :rocket:

**Comment by yadutaf** [comment]
Apparently, it does ;) Before we can consider merging, can you sign your commit ? A command like ``git commit -s --amend && git push -f`` should do the trick.

**Comment by h4cc** [comment]
@yadutaf Signed it.

Also added a sweet HHVM Badge :dart:

**Comment by VincentCasse** [comment]
Nice :)

But onyl your last commit is signed. Can you amend oldest commits ?

**Comment by h4cc** [comment]
@VincentCasse Hope i did it right.

**Comment by VincentCasse** [comment]
Yes it works!

Thanks for your contribution :)

**Comment by h4cc** [comment]
Badge is bright green and says: "HHVM - tested"

:confetti_ball: Congratulations! :confetti_ball:

**Pull request merged**
